version: '3.9'

services:
  controller:
    build: ./controller
    command: sh ./run.sh
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=5432
      - DB_LOGIN=${POSTGRES_ADMIN}
      - DB_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DEBUG=True
      - DB_HOST=postgres
    volumes:
      - ./controller/src:/app/controller
    depends_on:
      - postgres
  postgres:
    image: postgres
    # open port for debug
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dbdata:/var/lib/postgresql/data

