version: '3.9'

services:
  backend:
    build: ./controller
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=5432
      - DB_LOGIN=${POSTGRES_ADMIN}
      - DB_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DEBUG=True
      - DB_HOST=postgres
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CLIENT_GOOGLE_JSON=${CLIENT_GOOGLE_JSON}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./controller/src:/app/controller
    depends_on:
      - postgres
  
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${BACKEND_URL}
        YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "4200:4200"
    environment:
      - BACKEND_URL=http://backend:8080/api
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./frontend/src/app:/usr/src/app/src/app
      - ./frontend/src/assets:/usr/src/app/src/assets
    depends_on:
      - backend
  
  postgres:
    image: postgres
    # open port for debug
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
