CREATE TABLE irregular_verbs  (
    id INTEGER PRIMARY KEY,
    verb CHARACTER VARYING(255),
    past CHARACTER VARYING(255),
    past_participle CHARACTER VARYING(255), 
    verb_level INTEGER
);

COMMENT ON TABLE irregular_verbs IS 'Table to store irregular verbs dictionary';

COMMENT ON COLUMN irregular_verbs.id IS 'Unique identifier for each verb';
COMMENT ON COLUMN irregular_verbs.verb IS 'Present form';
COMMENT ON COLUMN irregular_verbs.past IS 'Past form';
COMMENT ON COLUMN irregular_verbs.past_participle IS 'Past participle form';
COMMENT ON COLUMN irregular_verbs.verb_level IS 'Difficult level';

INSERT INTO irregular_verbs (id, verb, past, past_participle, verb_level) VALUES
(1,'say','said','said',1),
(2,'make','made','made',1),
(3,'go','went','gone',1),
(4,'take','took','taken',1),
(5,'come','came','come',1),
(6,'see','saw','seen',1),
(7,'know','knew','known',1),
(8,'get','got','got/gotten',1),
(9,'give','gave','given',1),
(10,'find','found','found',1),
(11,'think','thought','thought',1),
(12,'tell','told','told',1),
(13,'become','became','become',1),
(14,'show','showed','shown',1),
(15,'leave','left','left',1),
(16,'feel','felt','felt',1),
(17,'put','put','put',1),
(18,'bring','brought','brought',1),
(19,'begin','began','begun',1),
(20,'keep','kept','kept',1),
(21,'hold','held','held',1),
(22,'write','wrote','written',1),
(23,'stand','stood','stood',1),
(24,'hear','heard','heard',1),
(25,'let','let','let',1),
(26,'mean','meant','meant',1),
(27,'set','set','set',1),
(28,'meet','met','met',1),
(29,'run','ran','run',1),
(30,'pay','paid','paid',1),
(31,'sit','sat','sat',1),
(32,'speak','spoke','spoken',1),
(33,'lie','lay','lain',1),
(34,'lead','led','led',1),
(35,'read','read','read',1),
(36,'grow','grew','grown',1),
(37,'lose','lost','lost',1),
(38,'fall','fell','fallen',1),
(39,'send','sent','sent',1),
(40,'build','built','built',1),
(41,'understand','understood','understood',1),
(42,'draw','drew','drawn',1),
(43,'break','broke','broken',1),
(44,'spend','spent','spent',1),
(45,'cut','cut','cut',1),
(46,'rise','rose','risen',1),
(47,'drive','drove','driven',1),
(48,'buy','bought','bought',1),
(49,'wear','wore','worn',1),
(50,'choose','chose','chosen',1),
(51,'abide','abode','abode',2),
(52,'arise','arose','arisen',2),
(53,'awake','awoke','awoken',2),
(54,'be','was/were','been',2),
(55,'bear','bore','born',2),
(56,'beat','beat','beaten',2),
(57,'befall','befell','befallen',2),
(58,'beget','begot','begotten',2),
(59,'bespeak','bespoke','bespoken',2),
(60,'bestride','bestrode','bestridden',2),
(61,'bet','bet','bet',2),
(62,'bid','bade/bid','bidden/bid',2),
(63,'bind','bound','bound',2),
(64,'bite','bit','bitten',2),
(65,'bleed','bled','bled',2),
(66,'blow','blew','blown',2),
(67,'breed','bred','bred',2),
(68,'broadcast','broadcast','broadcast',2),
(69,'burn','burnt','burnt',2),
(70,'burst','burst','burst',2),
(71,'can','could','',2),
(72,'cast','cast','cast',2),
(73,'deal','dealt','dealt',2),
(74,'dream','dreamt','dreamt',2),
(75,'drink','drank','drunk',2),
(76,'dwell','dwelt','dwelt',2),
(77,'eat','ate','eaten',2),
(78,'interweave','interwove','interwoven',2),
(79,'feed','fed','fed',2),
(80,'fight','fought','fought',2),
(81,'flee','fled','fled',2),
(82,'fling','flung','flung',2),
(83,'fly','flew','flown',2),
(84,'forbid','forbad(e)','forbidden',2),
(85,'forecast','forecast','forecast',2),
(86,'forget','forgot','forgotten',2),
(87,'forgive','forgave','forgiven',2),
(88,'forsake','forsook','forsaken',2),
(89,'foresee','foresaw','foreseen',2),
(90,'foretell','foretold','foretold',2),
(91,'freeze','froze','frozen',2),
(92,'grind','ground','ground',2),
(93,'hang','hung','hung',2),
(94,'have','had','had',2),
(95,'mistake','mistook','mistaken',2),
(96,'overhear','overheard','overheard',2),
(97,'oversleep','overslept','overslept',2),
(98,'rend','rent','rent',2),
(99,'rid','rid','rid',2),
(100,'ride','rode','ridden',2),
(101,'ring','rang','rung',2),
(102,'seek','sought','sought',2),
(103,'sell','sold','sold',2),
(104,'shake','shook','shaken',2),
(105,'shed','shed','shed',2),
(106,'shine','shone','shone',2),
(107,'shit','shit/shat','shit/shat',2),
(108,'shoot','shot','shot',2),
(109,'shrink','shrank','shrunk',2),
(110,'shrive','shrove','shriven',2),
(111,'steal','stole','stolen',2),
(112,'stick','stuck','stuck',2),
(113,'sting','stung','stung',2),
(114,'stink','stank','stunk',2),
(115,'stride','strode','stridden',2),
(116,'strike','struck','struck',2),
(117,'string','strung','strung',2),
(118,'strive','strove','striven',2),
(119,'swear','swore','sworn',2),
(120,'sweep','swept','swept',2),
(121,'swim','swam','swum',2),
(122,'swing','swung','swung',2),
(123,'teach','taught','taught',2),
(124,'tear','tore','torn',2),
(125,'throw','threw','thrown',2),
(126,'thrust','thrust','thrust',2),
(127,'tread','trod','trodden',2),
(128,'undertake','undertook','undertaken',2),
(129,'undo','undid','undone',2),
(130,'upset','upset','upset',2),
(131,'wake','woke','woken',2),
(132,'weave','wove','woven',2),
(133,'weep','wept','wept',2),
(134,'win','won','won',2),
(135,'wind','wound','wound',2);